### ISSUE TITLE
URLs to online program are prefaced by extra "https://ww2.amstat.org/meetings/jsm/2018/onlineprogram/"

### ISSUE THREAD

**Issue by benjamin-ackerman** [mine-cetinkaya-rundel/jsm2019-schedule#1]
I think this may have happened in the `scrape.R` script, line 100

**Comment by benjamin-ackerman** [comment]
I think if you replace `url = glue("http://ww2.amstat.org/meetings/jsm/2019/onlineprogram/{urls}")` with `url = urls` it should fix it!

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, fixed!
