### ISSUE TITLE
URLs work in "talk finder" but not "session schedule" tab

### ISSUE THREAD

**Issue by benjamin-ackerman** [mine-cetinkaya-rundel/jsm2019-schedule#2]
Similar to issue #1 but in the sessions table. Looks like "https://ww2.amstat.org/meetings/jsm/2018/onlineprogram/" is added to beginning of url

https://github.com/mine-cetinkaya-rundel/jsm2019-schedule/blob/f5ffe8f00c74cb56df225b88113fa5bd869391d7/scrape.R#L68

**Comment by mine-cetinkaya-rundel** [comment]
Thanks, should be fixed now!
